### PR TITLE
chore: add stagnant cargo lock

### PR DESCRIPTION
**Pull request by louisjoecodes**

### CODE REVIEW

**Comment by benfdking** [comment]
What version of Rust/Cargo are you running because I don't see that?

**Comment by benfdking** [comment]
Added to check https://github.com/quarylabs/quary/pull/157

**Comment by louisjoecodes** [comment]
rustc 1.78.0 (9b00956e5 2024-04-29)
cargo 1.78.0 (54d8815d0 2024-03-26)

**Comment by benfdking** [comment]
Rebase?

**Comment by louisjoecodes** [comment]
The locked flag is causing some issues

**Pull request closed without merging**
